# -*- coding: utf-8 -*-

from odoo import models, fields, api

class Insurance(models.Model):
    _name = 'healthiva.insurance'

    active = fields.Boolean(default=True)
    sequence_number=fields.Integer(string="Sequence Number")
    id_number=fields.Char(string="Identification Number")
    payer_code=fields.Char(string="Payer Code")
    group_number=fields.Char(string="Group Number of Insured Patient")
    group_name=fields.Char(string="Group Name")
    employerid=fields.Char(string="Insured's Group Employer ID")
    employer_name=fields.Char(string="Insured's Group Employer Name")
    plan_effective_date=fields.Datetime(string="Plan Effective Date/Time")
    plan_expiration_date=fields.Datetime(string="Plan Expiration Date/Time")
    authorization_info=fields.Char(string="Authorization Information")
    plan_type=fields.Char(string="Plan Type")
    insured_first_name=fields.Char(string="First Name of Insured")
    insured_middle_name=fields.Char(string="Middle Name of Insured")
    insured_last_name=fields.Char(string="Last Name of Insured")
    insured_relation=fields.Char(string="Insured's Relationship to Patient")
    assignment_benefits=fields.Char(string="Assignement of Benefits")
    coordinator_benefits=fields.Char(string="Coordinator of Benefits")
    primary_payer=fields.Char(string="Primary Payer")
    notice_admit_code=fields.Char(string="Notice of Admission Code")
    notice_admit_date=fields.Char(string="Notice of Admission Date/Time")
    report_eligibility_flag=fields.Char(string="Report of Eligibility Flag")
    report_eligibility_date=fields.Char(string="Report of Eligibility Date/Time")
    release_info_code=fields.Char(string="Release Information Code")
    preadmit_certification=fields.Char(string="Pre-admit Certification")
    verification_date=fields.Char(string="Verification Date/Time")
    verification_by=fields.Char(string="Verification By")
    agreement_type=fields.Char(string="Type of Agreement (Worker’s Compensation Flag)")
    bill_status=fields.Char(string="Billing Status")
    reserve_days=fields.Char(string="Lifetime Reserve Days")
    reserve_days_delay=fields.Char(string="Delay before Lifetime Reserve Days")
    company_plan_code=fields.Char(string="Company Plan Code")
    policy_number=fields.Char(string="Policy Number (Insurance Number/Subscriber Number/Member ID)")
    patient_id = fields.Many2one("res.partner", string="Patient")
    comment=fields.Text(string="Notes")
