# -*- coding: utf-8 -*-

from odoo import models, fields, api

class Provider(models.Model):
    _name = 'healthiva.provider'

    active = fields.Boolean(default=True)
    sequence_number=fields.Integer(string="Sequence Number")
    assigned_location=fields.Char(string="Assigned Patient Location")
    admission_type=fields.Char(string="Admission Type")
    preadmit_number=fields.Char(string="Preadmit Number")
    prior_location=fields.Char(string="Prior Patient Location")
    attending_doctor=fields.Char(string="Attending Doctor")
    referring_doctor=fields.Char(string="Referring Doctor")
    consulting_doctor=fields.Char(string="Consulting Doctor")
    hospital_service=fields.Char(string="Hospital Service")
    temp_location=fields.Char(string="Temporary Location")
    pretest_indicator=fields.Char(string="Preadmit Test Indicator")
    readmission=fields.Char(string="Re-admission Indicator")
    admit_source=fields.Char(string="Admit Source")
    ambulatory_status=fields.Char(string="Ambulatory Status")
    vip_indicator=fields.Char(string="VIP Indicator")
    admitting_doctor=fields.Char(string="Admitting Doctor")
    patient_type=fields.Char(string="Patient Type")
    visit_number=fields.Char(string="Visit Number")
    financial_class=fields.Char(string="Financial Class")
    charge_indicator=fields.Char(string="Charge Price Indicator")
    credit_rating=fields.Char(string="Credit Rating")
    contract_code=fields.Char(string="Contract Code")
    contract_date=fields.Date(string="Contract Effective Date")
    contract_total=fields.Char(string="Contract Amount")
    contract_period=fields.Char(string="Contract Period")
    interest_code=fields.Char(string="Interest Code")
    contract_code=fields.Char(string="Contract Code")
    tbd_code=fields.Char(string="Transfer to Bad Debt Code")
    tbd_date=fields.Date(string="Transfer to bad Debt Date")
    bda_code=fields.Char(string="Bad Debt Agency Code")
    bd_transfer_total=fields.Char(string="Bad Debt Transfer Amount")
    bd_recovery_total=fields.Char(string="Bad Debt Recovery Amount")
    delete_indicator=fields.Char(string="Delete Account Indicator")
    delete_date=fields.Date(string="Delete Account Date")
    discharge_disposition=fields.Char(string="Discharge Disposition")
    discharge_location=fields.Char(string="Discharged to Location")
    diet_type=fields.Char(string="Diet Type")
    service_location=fields.Char(string="Servicing Facility")
    bed_status=fields.Char(string="Bed Status")
    account_status=fields.Char(string="Account Status")
    pending_loc=fields.Char(string="Pending Location")
    prior_temp_location=fields.Char(string="Prior Temporary Location")
    admit_date=fields.Datetime(string="Admit Date/Time")
    discharge_date=fields.Datetime(string="Discharge Date/Time")
    current_balance=fields.Char(string="Current Patient Balance")
    adjustments_total=fields.Char(string="Total Adjustments")
    payments_total=fields.Char(string="Total Payments")
    alt_visitid=fields.Char(string="Alternate Visit ID")
    visit_indicator=fields.Char(string="Visit Indicator")
    other_provider=fields.Char(string="Other Healthcare Provider")
    patient_id = fields.Many2one("res.partner", string="Patient")
    comment=fields.Text(string="Notes")
    